[package]
name = "editor"
version = "0.1.0"
authors = ["doberan <doberankei@gmail.com>"]

# [dependencies.conrod]
# version = "0.53.0"
# features = ["gliun", "winit"]

[dependencies]
find_folder = "*"
rand="0.3.0"
